from app.core.config import Settings
from app.models.schemas import QueryResponse, Source
from app.services.retrieval import extract_requested_article


class GenerationService:
    missing_knowledge_message = "我还没有加载当前知识"

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def answer(self, question: str, sources: list[Source]) -> QueryResponse:
        if not sources:
            return self._missing_knowledge_answer()
        exact_article_sources = self._exact_article_sources(question, sources)
        if exact_article_sources is not None:
            if self.settings.enable_ai_generation and self.settings.model_provider == "openai-compatible":
                return self._remote_answer(question, exact_article_sources, exact_extraction=True)
            return self._local_exact_article_answer(exact_article_sources)
        if self.settings.enable_ai_generation and self.settings.model_provider == "openai-compatible":
            return self._remote_answer(question, sources)
        return self._local_answer(question, sources, generation_notice="AI generation disabled")

    def _exact_article_sources(self, question: str, sources: list[Source]) -> list[Source] | None:
        for source in sources:
            article_text = extract_requested_article(question, source.text)
            if article_text is None:
                continue
            exact_source = source.model_copy(update={"text": article_text})
            return [exact_source]
        return None

    def _local_exact_article_answer(self, sources: list[Source]) -> QueryResponse:
        article_text = sources[0].text
        return QueryResponse(
            answer=article_text,
            grounded_summary=article_text,
            sources=sources,
            used_supplemental_knowledge=False,
            generated_by_ai=False,
            generation_notice="Extracted exact article from knowledge base",
            supplemental_note=None,
        )

    def _local_answer(
        self,
        question: str,
        sources: list[Source],
        generation_notice: str = "Generated by local fallback",
    ) -> QueryResponse:
        if sources:
            top = sources[0]
            grounded = top.text[:500]
            return QueryResponse(
                answer=grounded,
                grounded_summary=grounded,
                sources=sources,
                used_supplemental_knowledge=False,
                generated_by_ai=False,
                generation_notice="Extracted from knowledge base",
                supplemental_note=None,
            )
        return self._missing_knowledge_answer(generation_notice=generation_notice)

    def _missing_knowledge_answer(self, generation_notice: str = "No matched knowledge-base content") -> QueryResponse:
        return QueryResponse(
            answer=self.missing_knowledge_message,
            grounded_summary=self.missing_knowledge_message,
            sources=[],
            used_supplemental_knowledge=False,
            generated_by_ai=False,
            generation_notice=generation_notice,
            supplemental_note=None,
        )

    def _remote_answer(
        self,
        question: str,
        sources: list[Source],
        exact_extraction: bool = False,
    ) -> QueryResponse:
        answer = self._langchain_agent_answer(question, sources, exact_extraction=exact_extraction)
        if answer is None:
            if exact_extraction and sources:
                return self._local_exact_article_answer(sources)
            return self._local_answer(question, sources, generation_notice="Generated by local fallback")
        try:
            answer = answer.strip()
        except AttributeError:
            if exact_extraction and sources:
                return self._local_exact_article_answer(sources)
            return self._local_answer(question, sources, generation_notice="Generated by local fallback")
        used_supplemental = not sources
        grounded = "已检索到相关内容。" if sources else "未检索到可引用的内容。"
        generation_notice = (
            "AI extracted answer from matched knowledge-base context"
            if exact_extraction
            else "AI generated with knowledge-base context"
            if sources
            else "AI generated without matched knowledge-base context"
        )
        return QueryResponse(
            answer=answer,
            grounded_summary=grounded,
            sources=sources,
            used_supplemental_knowledge=used_supplemental,
            generated_by_ai=True,
            generation_notice=generation_notice,
            supplemental_note="当前知识库没有检索到相关内容，回答基于通用模型知识。" if used_supplemental else None,
        )

    def _langchain_agent_answer(
        self,
        question: str,
        sources: list[Source],
        exact_extraction: bool = False,
    ) -> str | None:
        import httpx
        from langchain.agents import create_agent
        from langchain.tools import tool
        from langchain_openai import ChatOpenAI

        api_key = self.settings.openai_chat_api_key or self.settings.openai_api_key
        api_base = self.settings.openai_chat_api_base or self.settings.openai_api_base
        if not api_key:
            raise RuntimeError("APP_OPENAI_API_KEY or APP_OPENAI_CHAT_API_KEY is required for openai-compatible chat.")

        context = "\n\n".join(f"[{idx + 1}] {source.text}" for idx, source in enumerate(sources))

        @tool
        def get_retrieved_content() -> str:
            """Return the retrieved knowledge-base content that must be used to answer."""
            return context or "NO_RETRIEVED_CONTENT"

        if exact_extraction:
            system_prompt = (
                "You are a precise extraction agent for retrieved product documentation.\n"
                "Decision loop:\n"
                "1. Call get_retrieved_content.\n"
                "2. Extract only the answer requested by the user from that content.\n"
                "3. Return the final answer.\n"
                "Rules:\n"
                "- Use only get_retrieved_content as evidence.\n"
                "- For article/clause questions, output the complete matching article/clause text and do not include adjacent articles/clauses.\n"
                "- Do not summarize, rewrite, add explanations, or add general model knowledge.\n"
                "- Do not use source-preface phrases."
            )
        elif sources:
            system_prompt = (
                "You are a customer-facing product knowledge agent.\n"
                "Decision loop:\n"
                "1. Call get_retrieved_content.\n"
                "2. Decide which retrieved parts answer the user's question.\n"
                "3. Produce a concise answer in the user's language.\n"
                "Rules:\n"
                "- Use retrieved content as the primary source.\n"
                "- Extract the most accurate answer from retrieved content before adding any general model knowledge.\n"
                "- Do not say 'according to official documentation', 'based on retrieved official documentation', '根据官方文档', or similar source-preface phrases.\n"
                "- Do not tell the user to refer to document entries for detailed explanations.\n"
                "- If retrieved content and general model knowledge are both used, blend them into one coherent answer.\n"
                "- Do not label any section as 'Model supplemental note'."
            )
        else:
            system_prompt = (
                "You are a customer-facing product knowledge agent.\n"
                "There is no retrieved knowledge-base content. Answer from general knowledge only when useful, and briefly state that no matching knowledge-base content was found.\n"
                "Do not use the label 'Model supplemental note'."
            )

        try:
            http_client = httpx.Client(trust_env=False, timeout=60)
            model = ChatOpenAI(
                model=self.settings.chat_model,
                api_key=api_key,
                base_url=api_base,
                temperature=0.0 if exact_extraction else 0.2,
                http_client=http_client,
                extra_body={"thinking": {"type": "disabled"}},
            )
            agent = create_agent(model=model, tools=[get_retrieved_content], system_prompt=system_prompt)
            result = agent.invoke({"messages": [{"role": "user", "content": question}]})
        except Exception:
            return None
        finally:
            try:
                http_client.close()
            except UnboundLocalError:
                pass

        messages = result.get("messages", []) if isinstance(result, dict) else []
        for message in reversed(messages):
            if message.__class__.__name__ == "AIMessage" and isinstance(message.content, str) and message.content.strip():
                return message.content
        return None
